default_context:
  project_name: 'Anime-Recommender-Service'
  project_slug: 'anime-recommender-service'
  domain_main: 'anime-recommender-service.com'
  domain_staging: 'stag.anime-recommender-service.com'
  docker_swarm_stack_name_main: 'anime-recommender-service-com'
  docker_swarm_stack_name_staging: 'stag-anime-recommender-service-com'
  secret_key: 'acda980612ded9acb38ee4c4e0f4d0a3136dc00117b4321a5d237f0b264b0812'
  first_superuser: 'admin@anime-recommender-service.com'
  first_superuser_password: 'acda980612ded9acb38ee4c4e0f4d0a3136dc00117b4321a5d237f0b264b0812'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.anime-recommender-service.com", "https://stag.anime-recommender-service.com", "https://anime-recommender-service.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@anime-recommender-service.com'
  postgres_password: 'acda980612ded9acb38ee4c4e0f4d0a3136dc00117b4321a5d237f0b264b0812'
  pgadmin_default_user: 'admin@anime-recommender-service.com'
  pgadmin_default_user_password: 'acda980612ded9acb38ee4c4e0f4d0a3136dc00117b4321a5d237f0b264b0812'
  traefik_constraint_tag: 'anime-recommender-service.com'
  traefik_constraint_tag_staging: 'stag.anime-recommender-service.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:acda980612ded9acb38ee4c4e0f4d0a3136dc00117b4321a5d237f0b264b0812'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
